env:
  global:
    - CC_TEST_REPORTER_ID=92d8f685b76546be1fa92a36356cf142e8eb3852ac43c3449fa613ba8d69f4b8
sudo: false
language: node_js
node_js:
  - "10"
  - "12"
# keep the npm cache to speed up installs
cache:
  directories:
    - "$HOME/.npm"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
# after_success:
#   - npm run cov:send
#   - npm run cov:check
